namespace RobotStructuralMCP.RobotAPI.Com;

/// <summary>
/// Inventaire exhaustif des membres RobotOM appelés par <see cref="RobotComGateway"/>.
/// L'outil robot_verify_api compare cet inventaire à la bibliothèque de types installée.
/// Confidence :
///  - "sample"   : utilisé tel quel dans les exemples officiels du SDK Robot API ;
///  - "inferred" : déduit de la documentation / de la nomenclature RobotOM, à confirmer via robot_verify_api.
/// La liaison étant tardive (IDispatch), les noms d'interfaces ne servent qu'au diagnostic :
/// à l'exécution, seul le nom du membre compte.
/// </summary>
public static class RobotApiManifest
{
    public sealed record Entry(string Interface, string Member, string Usage, string Confidence);

    public static readonly IReadOnlyList<Entry> Members = new Entry[]
    {
        // Application / projet
        new("IRobotApplication", "Project", "connexion", "sample"),
        new("IRobotApplication", "Visible", "connexion", "sample"),
        new("IRobotApplication", "Interactive", "connexion, restauration de checkpoint", "sample"),
        new("IRobotApplication", "UserControl", "connexion", "sample"),
        new("IRobotApplication", "CmpntFactory", "panneaux, requêtes de résultats", "sample"),
        new("IRobotApplication", "Kernel", "dimensionnement acier (RDimServer)", "inferred"),
        new("IRobotProject", "Structure", "modèle", "sample"),
        new("IRobotProject", "Name", "infos projet", "sample"),
        new("IRobotProject", "FileName", "infos projet", "sample"),
        new("IRobotProject", "Type", "infos projet", "sample"),
        new("IRobotProject", "IsActive", "statut", "inferred"),
        new("IRobotProject", "Save", "robot_save_project", "sample"),
        new("IRobotProject", "SaveAs", "robot_save_project_as, checkpoints", "sample"),
        new("IRobotProject", "Open", "restore_checkpoint", "sample"),
        new("IRobotProject", "CalcEngine", "calcul", "sample"),
        new("IRobotProject", "Preferences", "normes actives", "inferred"),
        new("IRobotProjectPreferences", "GetActiveCode", "normes actives", "inferred"),
        new("IRobotStructure", "Nodes", "nœuds", "sample"),
        new("IRobotStructure", "Bars", "barres", "sample"),
        new("IRobotStructure", "Objects", "panneaux", "sample"),
        new("IRobotStructure", "Labels", "étiquettes", "sample"),
        new("IRobotStructure", "Cases", "cas de charges", "sample"),
        new("IRobotStructure", "Selections", "sélections", "sample"),
        new("IRobotStructure", "Results", "résultats", "sample"),
        new("IRobotStructure", "Groups", "groupes", "inferred"),
        new("IRobotStructure", "FiniteElems", "statistiques de maillage", "inferred"),
        // Serveurs de données
        new("IRobotNodeServer", "Create", "create_node", "sample"),
        new("IRobotNodeServer", "Get", "lecture nœud", "sample"),
        new("IRobotNodeServer", "GetAll", "get_nodes", "sample"),
        new("IRobotNodeServer", "Exist", "validation", "sample"),
        new("IRobotNodeServer", "Delete", "delete_node", "sample"),
        new("IRobotNodeServer", "FreeNumber", "numérotation", "sample"),
        new("IRobotNode", "Number", "lecture", "sample"),
        new("IRobotNode", "X", "lecture / move_node", "sample"),
        new("IRobotNode", "Y", "lecture / move_node", "sample"),
        new("IRobotNode", "Z", "lecture / move_node", "sample"),
        new("IRobotNode", "SetLabel", "assign_support", "sample"),
        new("IRobotNode", "HasLabel", "lecture étiquettes", "sample"),
        new("IRobotNode", "GetLabelName", "lecture étiquettes", "sample"),
        new("IRobotNode", "RemoveLabel", "retrait d'appui", "inferred"),
        new("IRobotBarServer", "Create", "create_bar", "sample"),
        new("IRobotBarServer", "Get", "lecture barre", "sample"),
        new("IRobotBarServer", "GetAll", "get_bars", "sample"),
        new("IRobotBarServer", "Exist", "validation", "sample"),
        new("IRobotBarServer", "Delete", "delete_bar", "sample"),
        new("IRobotBarServer", "FreeNumber", "numérotation", "sample"),
        new("IRobotBar", "StartNode", "lecture / update_bar", "sample"),
        new("IRobotBar", "EndNode", "lecture / update_bar", "sample"),
        new("IRobotBar", "Length", "lecture", "sample"),
        new("IRobotBar", "Gamma", "lecture / update_bar", "sample"),
        new("IRobotBar", "SetLabel", "assign_section / assign_material / assign_bar_release", "sample"),
        new("IRobotObjObjectServer", "CreateContour", "create_panel", "sample"),
        new("IRobotObjObjectServer", "Get", "lecture panneau", "sample"),
        new("IRobotObjObjectServer", "Exist", "validation", "inferred"),
        new("IRobotObjObjectServer", "Delete", "delete_panel", "inferred"),
        new("IRobotObjObjectServer", "FreeNumber", "numérotation", "sample"),
        new("IRobotObjObject", "Main", "attributs / géométrie panneau", "sample"),
        new("IRobotObjObject", "SetLabel", "épaisseur panneau", "sample"),
        new("IRobotObjObject", "Initialize", "création panneau", "sample"),
        new("IRobotObjObject", "Update", "création panneau / maillage", "sample"),
        new("IRobotObjObject", "Mesh", "paramètres de maillage", "inferred"),
        new("IRobotObjPart", "Attribs", "Meshed", "sample"),
        new("IRobotObjPart", "Geometry", "lecture contour", "inferred"),
        new("IRobotObjPartAttribs", "Meshed", "panneau maillé", "sample"),
        new("IRobotPointsArray", "SetSize", "contour", "sample"),
        new("IRobotPointsArray", "Set", "contour", "sample"),
        new("IRobotComponentFactory", "Create", "contour / requêtes", "sample"),
        // Étiquettes
        new("IRobotLabelServer", "Create", "création d'étiquettes", "sample"),
        new("IRobotLabelServer", "Store", "enregistrement d'étiquettes", "sample"),
        new("IRobotLabelServer", "Get", "lecture d'étiquettes", "sample"),
        new("IRobotLabelServer", "Exist", "validation", "sample"),
        new("IRobotLabelServer", "Delete", "delete_support", "inferred"),
        new("IRobotLabelServer", "IsUsed", "delete_support", "inferred"),
        new("IRobotLabelServer", "GetAvailableNames", "listes d'étiquettes", "sample"),
        new("IRobotLabel", "Data", "données d'étiquette", "sample"),
        new("IRobotMaterialData", "Type", "matériau", "sample"),
        new("IRobotMaterialData", "E", "matériau", "sample"),
        new("IRobotMaterialData", "NU", "matériau", "sample"),
        new("IRobotMaterialData", "RO", "matériau (poids volumique)", "sample"),
        new("IRobotMaterialData", "Kirchoff", "matériau", "sample"),
        new("IRobotMaterialData", "LX", "matériau (dilatation)", "inferred"),
        new("IRobotMaterialData", "RE", "matériau (limite élastique)", "inferred"),
        new("IRobotMaterialData", "RT", "matériau (résistance traction)", "inferred"),
        new("IRobotMaterialData", "LoadFromDBase", "matériau depuis base Robot", "inferred"),
        new("IRobotBarSectionData", "ShapeType", "section", "sample"),
        new("IRobotBarSectionData", "Type", "section", "sample"),
        new("IRobotBarSectionData", "Concrete", "section béton", "sample"),
        new("IRobotBarSectionData", "CalcNonstdGeometry", "section paramétrée", "sample"),
        new("IRobotBarSectionData", "CreateNonstd", "tube", "sample"),
        new("IRobotBarSectionData", "LoadFromDBase", "profil acier", "sample"),
        new("IRobotBarSectionData", "MaterialName", "section", "sample"),
        new("IRobotBarSectionData", "GetValue", "propriétés de section", "sample"),
        new("IRobotBarSectionData", "IsConcrete", "lecture section", "inferred"),
        new("IRobotBarSectionConcreteData", "SetValue", "section béton", "sample"),
        new("IRobotBarSectionConcreteData", "GetValue", "section béton", "sample"),
        new("IRobotBarSectionNonstdData", "SetValue", "tube", "sample"),
        new("IRobotThicknessData", "ThicknessType", "épaisseur", "sample"),
        new("IRobotThicknessData", "Data", "épaisseur", "sample"),
        new("IRobotThicknessData", "MaterialName", "épaisseur", "sample"),
        new("IRobotThicknessHomoData", "ThickConst", "épaisseur", "sample"),
        new("IRobotNodeSupportData", "UX", "appui", "sample"),
        new("IRobotNodeSupportData", "KX", "appui élastique", "sample"),
        new("IRobotNodeSupportData", "HX", "appui élastique en rotation", "inferred"),
        new("IRobotBarReleaseData", "StartNode", "relâchement", "sample"),
        new("IRobotBarReleaseData", "EndNode", "relâchement", "sample"),
        new("IRobotBarEndReleaseData", "UX", "relâchement", "sample"),
        // Cas, charges, combinaisons
        new("IRobotCaseServer", "CreateSimple", "create_load_case", "sample"),
        new("IRobotCaseServer", "CreateCombination", "create_combination", "sample"),
        new("IRobotCaseServer", "Get", "lecture cas", "sample"),
        new("IRobotCaseServer", "GetAll", "get_load_cases", "sample"),
        new("IRobotCaseServer", "Exist", "validation", "sample"),
        new("IRobotCaseServer", "Delete", "delete_load_case", "sample"),
        new("IRobotCaseServer", "FreeNumber", "numérotation", "sample"),
        new("IRobotCase", "Number", "lecture cas", "sample"),
        new("IRobotCase", "Name", "lecture cas", "sample"),
        new("IRobotCase", "Nature", "lecture cas", "sample"),
        new("IRobotCase", "Type", "lecture cas", "sample"),
        new("IRobotSimpleCase", "AnalizeType", "lecture cas", "sample"),
        new("IRobotSimpleCase", "Records", "charges", "sample"),
        new("IRobotSimpleCase", "GetAnalysisParams", "analyse modale", "inferred"),
        new("IRobotSimpleCase", "SetAnalysisParams", "analyse modale", "inferred"),
        new("IRobotLoadRecordMngr", "New", "ajout de charge", "sample"),
        new("IRobotLoadRecordMngr", "Get", "lecture de charge", "sample"),
        new("IRobotLoadRecordMngr", "Count", "lecture de charge", "sample"),
        new("IRobotLoadRecordMngr", "Delete", "delete_load", "inferred"),
        new("IRobotLoadRecord", "SetValue", "valeurs de charge", "sample"),
        new("IRobotLoadRecord", "GetValue", "valeurs de charge", "sample"),
        new("IRobotLoadRecord", "Objects", "objets chargés", "sample"),
        new("IRobotLoadRecord", "Type", "lecture de charge", "sample"),
        new("IRobotCaseCombination", "CaseFactors", "combinaisons", "sample"),
        new("IRobotCaseCombination", "CombinationType", "combinaisons", "inferred"),
        new("IRobotCaseFactorMngr", "New", "combinaisons", "sample"),
        new("IRobotCaseFactorMngr", "Get", "combinaisons", "sample"),
        new("IRobotCaseFactorMngr", "Count", "combinaisons", "sample"),
        new("IRobotCaseFactor", "CaseNumber", "combinaisons", "sample"),
        new("IRobotCaseFactor", "Factor", "combinaisons", "sample"),
        new("IRobotSelectionFactory", "Create", "sélections", "sample"),
        new("IRobotSelectionFactory", "CreateFull", "sélection de tous les panneaux", "sample"),
        new("IRobotSelection", "FromText", "sélections", "sample"),
        new("IRobotSelection", "ToText", "lecture de charge", "sample"),
        new("IRobotSelection", "Count", "sélections", "sample"),
        new("IRobotSelection", "Get", "sélections", "sample"),
        new("IRobotGroupServer", "GetCount", "groupes", "inferred"),
        new("IRobotGroupServer", "Get", "groupes", "inferred"),
        // Calcul / maillage
        new("IRobotCalcEngine", "Calculate", "run_analysis", "sample"),
        new("IRobotCalcEngine", "GenerateModel", "generate_mesh", "inferred"),
        new("IRobotObjMesh", "Params", "maillage", "inferred"),
        new("IRobotMeshParams", "SurfaceParams", "maillage", "inferred"),
        new("IRobotMeshSurfaceParams", "Generation", "maillage", "inferred"),
        new("IRobotMeshSurfaceParams", "Method", "maillage", "inferred"),
        new("IRobotMeshGeneration", "ElementSize", "maillage", "inferred"),
        new("IRobotMeshGeneration", "Type", "maillage", "inferred"),
        // Résultats
        new("IRobotResultServer", "Available", "statut de calcul", "sample"),
        new("IRobotResultServer", "Nodes", "résultats nœuds", "sample"),
        new("IRobotResultServer", "Bars", "résultats barres", "sample"),
        new("IRobotResultServer", "Query", "résultats panneaux", "sample"),
        new("IRobotNodeResultServer", "Displacements", "déplacements", "sample"),
        new("IRobotNodeResultServer", "Reactions", "réactions", "sample"),
        new("IRobotBarResultServer", "Forces", "efforts", "sample"),
        new("IRobotBarResultServer", "Displacements", "déplacements barres", "sample"),
        new("IRobotBarResultServer", "Deflections", "flèches", "sample"),
        new("IRobotBarResultServer", "Stresses", "contraintes", "sample"),
        new("IRobotNodeDisplacementServer", "Value", "déplacements", "sample"),
        new("IRobotNodeReactionServer", "Value", "réactions", "sample"),
        new("IRobotBarForceServer", "Value", "efforts", "sample"),
        new("IRobotResultQueryParams", "ResultIds", "résultats panneaux", "sample"),
        new("IRobotResultQueryParams", "Selection", "résultats panneaux", "sample"),
        new("IRobotResultQueryParams", "SetParam", "résultats panneaux", "sample"),
        new("IRobotResultRowSet", "MoveFirst", "résultats panneaux", "sample"),
        new("IRobotResultRowSet", "MoveNext", "résultats panneaux", "sample"),
        new("IRobotResultRowSet", "CurrentRow", "résultats panneaux", "sample"),
        new("IRobotResultRow", "GetValue", "résultats panneaux", "sample"),
        new("IRobotResultRow", "GetParam", "résultats panneaux", "sample"),
        new("IRobotResultRow", "IsAvailable", "résultats panneaux", "sample"),
        // Dimensionnement acier
        new("IRobotKernel", "GetExtension", "RDimServer", "inferred"),
        new("IRDimServer", "Mode", "dimensionnement acier", "inferred"),
        new("IRDimServer", "CalculEngine", "dimensionnement acier", "inferred"),
        new("IRDimServer", "Connection", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "GetCalcParam", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "GetCalcConf", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "SetCalcParam", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "SetCalcConf", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "Solve", "dimensionnement acier", "inferred"),
        new("IRDimCalcEngine", "Results", "dimensionnement acier", "inferred"),
        new("IRDimCalcParam", "SetObjsList", "dimensionnement acier", "inferred"),
        new("IRDimCalcParam", "SetLimitState", "dimensionnement acier", "inferred"),
        new("IRDimCalcParam", "SetLoadsList", "dimensionnement acier", "inferred"),
        new("IRDimAllRes", "Get", "dimensionnement acier", "inferred"),
        new("IRDimDetailedRes", "Ratio", "dimensionnement acier", "inferred"),
        new("IRDimDetailedRes", "GovernCaseName", "dimensionnement acier", "inferred"),
    };

    /// <summary>Valeurs d'énumérations utilisées (vérifiées à l'exécution par nom).</summary>
    public static readonly IReadOnlyList<(string Enum, string Value)> EnumValues = new (string, string)[]
    {
        ("IRobotLabelType", "I_LT_SUPPORT"), ("IRobotLabelType", "I_LT_BAR_SECTION"), ("IRobotLabelType", "I_LT_MATERIAL"),
        ("IRobotLabelType", "I_LT_BAR_RELEASE"), ("IRobotLabelType", "I_LT_PANEL_THICKNESS"),
        ("IRobotObjectType", "I_OT_NODE"), ("IRobotObjectType", "I_OT_BAR"), ("IRobotObjectType", "I_OT_PANEL"), ("IRobotObjectType", "I_OT_CASE"),
        ("IRobotComponentType", "I_CT_POINTS_ARRAY"), ("IRobotComponentType", "I_CT_RESULT_QUERY_PARAMS"),
        ("IRobotMaterialType", "I_MT_STEEL"), ("IRobotMaterialType", "I_MT_CONCRETE"), ("IRobotMaterialType", "I_MT_OTHER"),
        ("IRobotBarSectionShapeType", "I_BSST_CONCR_BEAM_RECT"), ("IRobotBarSectionShapeType", "I_BSST_CONCR_COL_R"),
        ("IRobotBarSectionShapeType", "I_BSST_CONCR_COL_C"), ("IRobotBarSectionShapeType", "I_BSST_TUBE"), ("IRobotBarSectionShapeType", "I_BSST_RECT"),
        ("IRobotBarSectionType", "I_BST_NS_TUBE"), ("IRobotBarSectionType", "I_BST_NS_RECT"),
        ("IRobotBarSectionConcreteDataValue", "I_BSCDV_BEAM_B"), ("IRobotBarSectionConcreteDataValue", "I_BSCDV_BEAM_H"),
        ("IRobotBarSectionConcreteDataValue", "I_BSCDV_COL_B"), ("IRobotBarSectionConcreteDataValue", "I_BSCDV_COL_H"),
        ("IRobotBarSectionConcreteDataValue", "I_BSCDV_COL_DE"),
        ("IRobotBarSectionNonstdDataValue", "I_BSNDV_TUBE_D"), ("IRobotBarSectionNonstdDataValue", "I_BSNDV_TUBE_T"),
        ("IRobotBarSectionNonstdDataValue", "I_BSNDV_RECT_B"), ("IRobotBarSectionNonstdDataValue", "I_BSNDV_RECT_H"), ("IRobotBarSectionNonstdDataValue", "I_BSNDV_RECT_T"),
        ("IRobotBarSectionDataValue", "I_BSDV_AX"), ("IRobotBarSectionDataValue", "I_BSDV_IX"),
        ("IRobotBarSectionDataValue", "I_BSDV_IY"), ("IRobotBarSectionDataValue", "I_BSDV_IZ"),
        ("IRobotThicknessType", "I_TT_HOMOGENEOUS"),
        ("IRobotCaseNature", "I_CN_PERMANENT"), ("IRobotCaseNature", "I_CN_EXPLOATATION"), ("IRobotCaseNature", "I_CN_WIND"),
        ("IRobotCaseNature", "I_CN_SNOW"), ("IRobotCaseNature", "I_CN_TEMPERATURE"), ("IRobotCaseNature", "I_CN_ACCIDENTAL"), ("IRobotCaseNature", "I_CN_SEISMIC"),
        ("IRobotCaseAnalizeType", "I_CAT_STATIC_LINEAR"), ("IRobotCaseAnalizeType", "I_CAT_STATIC_NONLINEAR"),
        ("IRobotCaseAnalizeType", "I_CAT_DYNAMIC_MODAL"), ("IRobotCaseAnalizeType", "I_CAT_STATIC_FLAMB"), ("IRobotCaseAnalizeType", "I_CAT_COMB"),
        ("IRobotCaseType", "I_CT_SIMPLE"), ("IRobotCaseType", "I_CT_COMBINATION"),
        ("IRobotCombinationType", "I_CBT_ULS"), ("IRobotCombinationType", "I_CBT_SLS"), ("IRobotCombinationType", "I_CBT_ACC"),
        ("IRobotLoadRecordType", "I_LRT_DEAD"), ("IRobotLoadRecordType", "I_LRT_NODE_FORCE"), ("IRobotLoadRecordType", "I_LRT_BAR_UNIFORM"),
        ("IRobotLoadRecordType", "I_LRT_BAR_FORCE_CONCENTRATED"), ("IRobotLoadRecordType", "I_LRT_UNIFORM"), ("IRobotLoadRecordType", "I_LRT_BAR_THERMAL"),
        ("IRobotDeadRecordValues", "I_DRV_Z"), ("IRobotDeadRecordValues", "I_DRV_ENTIRE_STRUCTURE"),
        ("IRobotNodeForceRecordValues", "I_NFRV_FX"), ("IRobotNodeForceRecordValues", "I_NFRV_CZ"),
        ("IRobotBarUniformRecordValues", "I_BURV_PX"), ("IRobotBarUniformRecordValues", "I_BURV_PZ"),
        ("IRobotBarForceConcentrateRecordValues", "I_BFCRV_FZ"), ("IRobotBarForceConcentrateRecordValues", "I_BFCRV_X"), ("IRobotBarForceConcentrateRecordValues", "I_BFCRV_REL"),
        ("IRobotUniformRecordValues", "I_URV_PZ"), ("IRobotUniformRecordValues", "I_URV_LOCAL_SYSTEM"),
        ("IRobotBarThermalRecordValues", "I_BTRV_TX"),
        ("IRobotMeshGenerationType", "I_MGT_ELEMENT_SIZE"),
        ("IRobotResultParamType", "I_RPT_RESULT_POINT_TYPE"), ("IRobotResultParamType", "I_RPT_NODE"),
        ("IRobotResultPointType", "I_RPT_NODE"), ("IRobotResultQueryReturnType", "I_RQRT_DONE"),
        ("IRDimServerMode", "I_DSM_STEEL"), ("IRDimCalcParamVerifType", "I_DCPVT_MEMBERS_VERIF"),
        ("IRDimCalcParamLimitStateType", "I_DCPLST_ULTIMATE"),
    };
}
